version: "3.9"

services:
  fastapi-app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: fastapi_app
    ports:
      - "8001:8001"
    depends_on:
      - desafiocotacoes
      - postgres
    networks:
      - backend

  desafiocotacoes:
    image: mostela/desafiocotacoes:latest
    container_name: desafiocotacoes_service
    ports:
      - "3000:3000"
    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres_service
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: amigoz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
